- name: Copy Redis repo file to Redis host.
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/

- name: Install Redis.
  ansible.builtin.yum:
    name: redis-6.2.7
    state: installed

- name: Update Redis configuration - Listen address.
  ansible.builtin.replace:
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    path: /etc/redis.conf

- name: Start Redis DB
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: redis