- name: Copy MongoDb repo file
  ansible.builtin.copy:
    src:  mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: MongoDb installation
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDb Listen Ip Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDb service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: mongod

- name: Download and unzip Mongodb application.
  include_role:
    name: common
    tasks_from: download
  debugger: on_skipped

- name: Load MongoDb Catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users