- name: Play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Variable from Play level
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Variables from a file
  hosts: all
  vars_files:
    sample-vars.yaml
  tasks:
    - name: File level variable
      vars:
        URL: overridden.example.com
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Variable defined at task level
  hosts: all
  vars_files:
    sample-vars.yaml
  tasks:
    - name: Task level variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Variable defined in inventory file
  hosts: all
  tasks:
    - name: Print inventory variable
      ansible.builtin.debug:
        msg: URL = {{URL}}