- name: Play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Variable from Play level
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Variables from a file
  hosts: all
  var_file:
    sample-vars.yaml
  tasks:
    ansible.builtin.debug:
      msg: URL = {{URL}}