- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: t3.micro
    security_group_id: sg-03dc99c7c771a43f0
    image: ami-0b55b2bdf150da270
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
        count: 1
        group_id: "{{ security_group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-0d493668
        assign_public_ip: yes
        instance_tags:
          Name: Check-Instance
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_ip }}"
      wait_for_connection:
        delay: 30
        timeout: 120
      loop: "{{ ec2.instances }}"

- name: New play to execute role to test
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - "{{ role_name }}"
  ignore_errors: True

- name: Terminate instances
  hosts: localhost
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
        region: "{{ region }}"