# yum install nginx -y

# curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"

# cd /usr/share/nginx/html
# rm -rf *
# unzip /tmp/frontend.zip
# mv frontend-main/static/* .
# mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf

# systemctl restart nginx


- name: Nginx installation
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Download and unip frontend application.
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip
    remote_src: yes

- name: Recursively remove previous Nginx installation
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

