# yum install nginx -y

# curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"

# cd /usr/share/nginx/html
# rm -rf *
# mv frontend-main/static/* .
# mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf

# systemctl restart nginx


- name: Nginx installation
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Download and Extract frontend application.
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Recursively remove previous Nginx installation
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Copy frontend content to nginx path
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy frontend configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: nginx