#- name: Copy mysql repo file
#  ansible.builtin.copy:
#    src: mysql.repo
#    dest: /etc/yum.repos.d/

- name: Download mysql repo
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name: Start MySQL.
  ansible.builtin.systemd:
    name: mysqld
    state: started

- name: Trying MYSQL login
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
  register: mysql_stat
  ignore_errors: true

- name: Reset root password
  when: mysql_stat.failed
  block:
    - name: Copy rootpass query
      ansible.builtin.copy:
        src: rootpass.sql
        dest: /tmp/

    - name: Obtain Default Root Password.
      when: mysql_stat.failed
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_ROOT_PASSWD

    - name: Reset default root password
      when: mysql_stat.failed
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWD.stdout}}" </tmp/rootpass.sql

- name: Plugin check
  ansible.builtin.shell: echo 'show plugins'|mysql -uroot -p'RoboShop@1'| grep validate_password
  register: plugin_check
  ignore_errors: yes

- name: Remove plugin
  when: plugin_check.rc == 0
  block:
    - name: Copy the plugin.sql file
      ansible.builtin.copy:
        src: plugin.sql
        dest: /tmp
    - name: Plugin removal
      ansible.builtin.shell: mysql -uroot -pRoboShop@1 </tmp/plugin.sql

- name: Download and Unarchive Shipping schema.
  ansible.builtin.include_role:
    name: common
    task_from: download

- name: Load Shipping Schema
  ansible.builtin.shell: mysql -u root -pRoboShop@1 </tmp/shipping.sql