#1. So let's switch to the `roboshop` user and run the following commands.
#
#$ curl -s -L -o /tmp/catalogue.zip "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
#$ cd /home/roboshop
#$ unzip /tmp/catalogue.zip
#$ mv catalogue-main catalogue
#$ cd /home/roboshop/catalogue
#$ npm install
#
#```
#
#1. Update SystemD file with correct IP addresses
#
#Update `MONGO_DNSNAME` with MongoDB Server IP
#
#2. Now, lets set up the service with systemctl.
#
## mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
## systemctl daemon-reload
## systemctl start catalogue
## systemctl enable catalogue


- name: Install yum repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install a list of packages (suitable replacement for 2.11 loop deprecation warning)
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Create user 'roboshop'
  ansible.builtin.user:
    name: roboshop
    comment: John Doe

- name: Download and unzip Catalogue application.
  include_role:
    name: common
    tasks_from: download
  become_user: roboshop

- name: Copy catalogue content to roboshop's home path
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: yes

- name: Install nodejs packages
  community.general.npm:
    path: /home/roboshop/catalogue
