- name: Install Nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install Nodejs packages
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Setup User, {{COMPONENT}} application code.
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install nodejs dependencies.
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Start {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd