- name: Install Nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install Nodejs packages
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Create Application user
  ansible.builtin.user:
    name: roboshop
    comment: Application user

- name: Install {{COMPONENT}} application code.
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Cleanup Old Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Copy {{COMPONENT}} content to the application path.
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

- name: Install nodejs dependencies.
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Start {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd