- name: Python3 installation
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed


- name: Setup application user and the application.
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install python dependencies
  ansible.builtin.pip:
    chdir: /home/roboshop/{{COMPONENT}}
    requirements: requirements.txt
    executable: pip3

- name: Update User id in application configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{APP_USER.uid}}

- name: Update Group id in application configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{APP_USER.group}}

- name: Start the Payment Service.
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd