- name: Copy systemd service file.
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Starting {{COMPONENT}} service.
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    daemon-reload: yes
    enabled: yes